server:
  port: 40000

spring:
  application:
    name: @project.artifactId@
  profiles:
    include: info

logging:
  config: classpath:log4j2-prod.yml

eureka:
  instance:
    hostname: localhost
  client:
    registerWithEureka: false
    fetchRegistry: false
    serviceUrl:
      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/
